import time
import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.utils import formataddr, formatdate, make_msgid
from typing import Optional

from app.config import settings

logger = logging.getLogger(__name__)

SEVERITY_META = {
    "P0": {"border": "#FC8181", "badge_bg": "#E53E3E", "header_bg": "#FFF5F5", "label": "CRITICAL"},
    "P1": {"border": "#F6AD55", "badge_bg": "#DD6B20", "header_bg": "#FFFAF0", "label": "HIGH"},
    "P2": {"border": "#63B3ED", "badge_bg": "#3182CE", "header_bg": "#EBF8FF", "label": "MEDIUM"},
}

def _build_html(
    subject: str,
    severity: str,
    body: str,
    incident_id: Optional[str],
    trace_id: Optional[str],
    service_name: Optional[str],
    ticket_url: Optional[str],
    timestamp: str,
) -> str:
    sm = SEVERITY_META.get(severity, SEVERITY_META["P0"])

    ticket_cell = (
        f'<a href="{ticket_url}" style="color:#3182CE;text-decoration:none;">{incident_id}</a>'
        if ticket_url else (incident_id or "N/A")
    )

    body_html = "\n".join(
        f"<p style='margin:6px 0'>{line}</p>"
        for line in body.strip().splitlines()
        if line.strip()
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
</head>
<body style="margin:0;padding:24px;background:#F7FAFC;
             font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#2D3748;">

  <div style="max-width:600px;margin:0 auto;background:#fff;
              border:1px solid {sm['border']};border-radius:8px;overflow:hidden;">

    <!-- Header -->
    <div style="background:{sm['header_bg']};border-bottom:1px solid {sm['border']};padding:20px 24px;">
      <span style="display:inline-block;background:{sm['badge_bg']};color:#fff;
                   font-size:11px;font-weight:700;letter-spacing:.8px;
                   padding:3px 10px;border-radius:4px;text-transform:uppercase;">
        {severity} — {sm['label']}
      </span>
      <h1 style="margin:10px 0 0;font-size:17px;font-weight:600;color:#1A202C;">
        {subject}
      </h1>
    </div>

    <!-- Meta table -->
    <table style="width:100%;border-collapse:collapse;font-size:13px;padding:0;">
      <tr style="border-bottom:1px solid #EDF2F7;">
        <td style="padding:10px 24px;color:#718096;width:120px;">Incident ID</td>
        <td style="padding:10px 24px;">{ticket_cell}</td>
      </tr>
      <tr style="border-bottom:1px solid #EDF2F7;">
        <td style="padding:10px 24px;color:#718096;">Service</td>
        <td style="padding:10px 24px;">{service_name or "N/A"}</td>
      </tr>
      <tr style="border-bottom:1px solid #EDF2F7;">
        <td style="padding:10px 24px;color:#718096;">Trace ID</td>
        <td style="padding:10px 24px;font-family:monospace;font-size:12px;">{trace_id or "N/A"}</td>
      </tr>
      <tr>
        <td style="padding:10px 24px;color:#718096;">Time (UTC)</td>
        <td style="padding:10px 24px;">{timestamp}</td>
      </tr>
    </table>

    <!-- Body -->
    <div style="padding:16px 24px 24px;font-size:14px;
                line-height:1.7;border-top:1px solid #EDF2F7;">
      {body_html}
    </div>

    <!-- Footer -->
    <div style="background:#F7FAFC;border-top:1px solid #EDF2F7;
                padding:12px 24px;font-size:11px;color:#A0AEC0;">
      Generated by the Autonomous SRE Healing Engine &nbsp;·&nbsp;
      Do <strong>not</strong> reply — update the Jira ticket for all communications.
    </div>

  </div>
</body>
</html>"""

def send_group_email(
    subject: str | None = None,
    body: str | None = None,
    severity: str = "P0",
    incident_id: Optional[str] = None,
    trace_id: Optional[str] = None,
    service_name: Optional[str] = None,
    ticket_url: Optional[str] = None,
) -> dict:
    """
    Sends an HTML incident email via SMTP to the on-call group
    defined in settings.ONCALL_EMAIL_GROUP.

    Called by the SRE engine for:
      - Tier 3 escalations    → subject: "[P0 INCIDENT - MANUAL INTERVENTION REQUIRED]"
      - HEALING_FAILED events → subject: "[HEALING_FAILED - {service_name}]"

    Args:
        subject:      Email subject line.
        body:         Incident details (RCA, action attempted, current error state).
        severity:     P0 | P1 | P2 — controls badge color and urgency label.
        incident_id:  Jira ticket ID (e.g. "SRE-4821").
        trace_id:     GCP trace ID for log correlation.
        service_name: Affected service name.
        ticket_url:   Full Jira URL — rendered as a clickable link in the email.

    Returns:
        dict:
            success          (bool) — True if SMTP server accepted the message.
            message_id       (str)  — RFC 2822 Message-ID for audit trail.
            recipients       (list) — Addresses the email was dispatched to.
            recipients_count (int)  — Number of recipients.
            timestamp        (str)  — ISO 8601 UTC send time.
            error            (str)  — Present only on failure.
    """
    recipients = settings.ONCALL_EMAIL_GROUP
    timestamp  = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    message_id = make_msgid(domain=settings.SRE_EMAIL_SENDER.split("@")[-1])

    if not recipients:
        logger.error("send_group_email: ONCALL_EMAIL_GROUP is empty in settings.py")
        return {
            "success":   False,
            "error":     "ONCALL_EMAIL_GROUP is empty — add recipients to settings.py",
            "message_id": message_id,
        }

    html_body = _build_html(
        subject, severity, body,
        incident_id, trace_id, service_name, ticket_url, timestamp,
    )

    msg = MIMEMultipart()                          # multipart keeps headers clean
    msg["Subject"]    = subject
    msg["From"]       = formataddr(("SRE Engine", settings.SRE_EMAIL_SENDER))
    msg["To"]         = ", ".join(recipients)
    msg["Date"]       = formatdate(localtime=False)
    msg["Message-ID"] = message_id
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    try:
        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT, timeout=10) as server:
            server.ehlo()
            if settings.SMTP_USE_TLS:
                server.starttls()
                server.ehlo()
            server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
            server.sendmail(settings.SRE_EMAIL_SENDER, recipients, msg.as_string())

        logger.info(
            f"[EMAIL SENT] id={message_id} subject='{subject}' "
            f"to={recipients} severity={severity}"
        )
        return {
            "success":          True,
            "message_id":       message_id,
            "recipients":       recipients,
            "recipients_count": len(recipients),
            "timestamp":        timestamp,
        }

    except smtplib.SMTPAuthenticationError:
        error = "SMTP authentication failed — check SMTP_USER / SMTP_PASSWORD in settings.py"
        logger.error(f"send_group_email: {error}")
        return {"success": False, "error": error, "message_id": message_id}

    except smtplib.SMTPRecipientsRefused as e:
        error = f"Recipients refused by SMTP server: {list(e.recipients.keys())}"
        logger.error(f"send_group_email: {error}")
        return {"success": False, "error": error, "message_id": message_id}

    except smtplib.SMTPConnectError:
        error = f"Could not connect to SMTP server {settings.SMTP_HOST}:{settings.SMTP_PORT}"
        logger.error(f"send_group_email: {error}")
        return {"success": False, "error": error, "message_id": message_id}

    except smtplib.SMTPException as e:
        error = f"SMTP error: {e}"
        logger.error(f"send_group_email: {error}")
        return {"success": False, "error": error, "message_id": message_id}

    except Exception as e:
        logger.exception("send_group_email: unexpected error")
        return {"success": False, "error": str(e), "message_id": message_id}
